---
name: Woke - Non-Inclusive Language Detection

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  woke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Get changed files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        id: changed-files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run woke
        uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0 # v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
          woke-args: ${{ steps.changed-files.outputs.all_changed_files }}
