---
name: Woke - Non-Inclusive Language Detection

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  woke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Get changed files
        uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run woke
        uses: get-woke/woke-action@v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
          woke-args: ${{ steps.changed-files.outputs.all_changed_files }}
